### ISSUE TITLE
[Bug] pwa doesn’t work as intented on iOS

### ISSUE THREAD

**Issue by Magrid0** [schlagmichdoch/PairDrop#330] opened 2024-09-07 07:59 UTC
**Describe the bug**
Only a bookmark that open the link in safari is created instead of a full screen standalone web app

**To Reproduce**
1. Go to 'pairdrop.net'
2. Click on 'share'
3. Scroll down to 'add to home screen'
4. Click on 'add'
5. Go to the home screen and see the error

**Expected behavior**
A full screen pwa should’ve been created

**Screenshots**

https://github.com/user-attachments/assets/4d0e2e49-04c2-404f-85b2-fc1f1f3c19cf

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 18
 - Browser: safari
 - Version: latest

**Bug occurs on official PairDrop instance https://pairdrop.net/**
Yes
Version: v1.10.10

**Bug occurs on self-hosted PairDrop instance**
No

**Comment by schlagmichdoch** [comment] 2024-09-07 10:42
Duplicate of #264. 

This will be part of the new release `v2.0`. Stay tuned!

**Closed by schlagmichdoch** 2024-09-07 10:42 UTC
Labels: bug
