### ISSUE TITLE
Increase transmission speed [Friendly question]

### ISSUE THREAD

**Issue by XHyperDEVX** [schlagmichdoch/PairDrop#125] opened 2023-07-01 11:02 UTC
Hello,

I am using a self-hosted instance of Pairdrop on my Linux server. Unfortunately the transfer speed is quite slow. e.g. a 20MB file takes 15 seconds. This is not acceptable for me.

How can I increase the transfer speed/what throttles it?

**Comment by schlagmichdoch** [comment] 2023-07-07 13:48
Hi @XHyperDEVX ,

There is already an issue regarding the tranfer speed #44.

Apparently, the bottleneck seems to be the webrtc implementation introduced by Snapdrop. I will try to find a way to speed up the transfer by increasing the chunk size, using multiple data channels simultaneously and sending continously without waiting for the receiving end to confirm the receival.

Currently, I'm still trying to understand where the problem is exactly and how to tackle it so feel free to take a look at the current implementation yourself: https://github.com/schlagmichdoch/PairDrop/blob/29b91cb17aa7e830f1cb6a6659ac5e2c0b5b265e/public/scripts/network.js#L981

**Comment by XHyperDEVX** [comment] 2023-07-07 14:21
> Hi @XHyperDEVX ,
> 
> There is already an issue regarding the tranfer speed #44.
> 
> Apparently, the bottleneck seems to be the webrtc implementation introduced by Snapdrop. I will try to find a way to speed up the transfer by increasing the chunk size, using multiple data channels simultaneously and sending continously without waiting for the receiving end to confirm the receival.
> 
> Currently, I'm still trying to understand where the problem is exactly and how to tackle it so feel free to take a look at the current implementation yourself:
> 
> https://github.com/schlagmichdoch/PairDrop/blob/29b91cb17aa7e830f1cb6a6659ac5e2c0b5b265e/public/scripts/network.js#L981

Many thanks for their efforts!
Unfortunately I know little about code, but I'll take a look.

They can't say what they estimate when they can fix it or at least how much faster the transfer will run?

**Comment by schlagmichdoch** [comment] 2023-09-18 21:43
After we have just successfully implemented #55 and #35, increasing the transfer speed is the next priority. I'm not sure how much faster this is gonna be.

I'll close this as duplicate of #44

**Closed by schlagmichdoch** 2023-09-18 21:43 UTC
Labels: duplicate, question
