### ISSUE TITLE
[Enhancement] : config for devices

### ISSUE THREAD

**Issue by Yumega** [schlagmichdoch/PairDrop#153] opened 2023-09-15 16:09 UTC
**What problem is solved by the new feature**

Make it more convenient.

**Describe the feature**

Docker compose add configuration for all devices which have fixed ip address.
because they have fixed ip, the docker configuration can give the device a fixed name, and can enable accept files by default.

after the configuration set, we don’t need change device name, and we don’t need pair device everytime the cookies cleaned on all the devices.

**Comment by schlagmichdoch** [comment] 2023-09-18 21:37
I'll close this as a duplicate of #143. Please add your additional ideas over there.

The pair secrets and the edited display name are only saved on the devices and never on the server, so this will not be possible.  

Also, try installing PairDrop as PWA on your devices to prevent them from clearing PairDrops cookies.

**Closed by schlagmichdoch** 2023-09-18 21:37 UTC
Labels: enhancement
