### ISSUE TITLE
 [Bug] Uncaught exception on openwrt arm64

### ISSUE THREAD

**Issue by 9thChasingWindGirl** [schlagmichdoch/PairDrop#308] opened 2024-06-22 01:05 UTC
> pairdrop@1.10.8 start
> node server/index.js

PairDrop is running on port 60126
----- Uncaught exception -----
TypeError: Cannot read properties of undefined (reading 'substring')
    at Peer._setIP (file:///mnt/mmcblk0p27/PairDrop/server/peer.js:54:21)
    at new Peer (file:///mnt/mmcblk0p27/PairDrop/server/peer.js:15:14)
    at WebSocketServer.<anonymous> (file:///mnt/mmcblk0p27/PairDrop/server/ws-server.js:18:76)
    at WebSocketServer.emit (node:events:517:28)
    at WebSocketServer.completeUpgrade (/mnt/mmcblk0p27/PairDrop/node_modules/ws/lib/websocket-server.js:436:5)
    at WebSocketServer.handleUpgrade (/mnt/mmcblk0p27/PairDrop/node_modules/ws/lib/websocket-server.js:344:10)
    at Server.upgrade (/mnt/mmcblk0p27/PairDrop/node_modules/ws/lib/websocket-server.js:119:16)
    at Server.emit (node:events:517:28)
    at onParserExecuteCommon (node:_http_server:938:14)
    at onParserExecute (node:_http_server:824:3)
----- Exception origin -----
uncaughtException

**Comment by schlagmichdoch** [comment] 2024-06-22 09:24
What node and openwrt version are you running?

**Comment by 9thChasingWindGirl** [comment] 2024-06-22 12:22
> What node and openwrt version are you running?

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='02.06.2024'
DISTRIB_TARGET='qualcommax/ipq60xx'
DISTRIB_ARCH='aarch64_cortex-a53'

and node ver is v18.20.3

In fact, all functions are normal at present, just in case, I noticed this log, so I submitted issue.

**Comment by 9thChasingWindGirl** [comment] 2024-06-22 12:25
Is there luci for openwrt? Running paridrop manually is not easy to manage.

**Comment by schlagmichdoch** [comment] 2024-07-13 15:23
I can reproduce this on my Ubuntu testing machine as well. Apparently, in some cases `request.connection.remoteAddress` can be `undefined` when a socket is closed immediately after opening which results in this error because the code assumes it to be a String. This is not critical though, as the socket is then closed anyway.
https://github.com/schlagmichdoch/PairDrop/blob/e6f2c776dc4b5877bf14ec5a3a8a12be2e9599a4/server/peer.js#L45-L55

Apparently, `request.connection` is also [deprecated](https://nodejs.org/docs/latest-v12.x/api/http.html#http_request_connection) and should be replaced by `request.socket`.
Line 50 will then simply change to:
```javascript
            this.ip = request.socket.remoteAddress ?? '';
```

I'll add this fix in the next version. Thanks for reporting!



> luci-app-pairdrop maybe like this

Although I like the idea of having an app for openwrt, I'll not prioritize that for now as this would probably include [porting the node.js express server to C](https://openwrt.org/docs/guide-developer/helloworld/start). If anyone is willing to create a wrapper for that, I'd gladly assist.

**Comment by 9thChasingWindGirl** [comment] 2024-07-13 16:01
> I can reproduce this on my Ubuntu testing machine as well. Apparently, in some cases `request.connection.remoteAddress` can be `undefined` when a socket is closed immediately after opening which results in this error because the code assumes it to be a String. This is not critical though, as the socket is then closed anyway.
> https://github.com/schlagmichdoch/PairDrop/blob/e6f2c776dc4b5877bf14ec5a3a8a12be2e9599a4/server/peer.js#L45-L55
> 
> Apparently, `request.connection` is also [deprecated](https://nodejs.org/docs/latest-v12.x/api/http.html#http_request_connection) and should be replaced by `request.socket`.
> Line 50 will then simply change to:
> ```javascript
>             this.ip = request.socket.remoteAddress ?? '';
> ```
> 
> I'll add this fix in the next version. Thanks for reporting!
> 
> 
> 
> > luci-app-pairdrop maybe like this
> 
> Although I like the idea of having an app for openwrt, I'll not prioritize that for now as this would probably include [porting the node.js express server to C](https://openwrt.org/docs/guide-developer/helloworld/start). If anyone is willing to create a wrapper for that, I'd gladly assist.

The project is running well on OpenWRT, looking forward to your next improvement or update

**Comment by schlagmichdoch** [comment] 2024-07-18 17:13
Fixed by [04d65da](https://github.com/schlagmichdoch/PairDrop/commit/04d65da7793700a68a03ca1e024c7abb643b5979)

**Closed by schlagmichdoch** 2024-07-18 17:13 UTC
Labels: bug, enhancement, self-hosted
