### ISSUE TITLE
Bug:/Enhancement:/Feature Request: share menu with Android 13 not working

### ISSUE THREAD

**Issue by holgerimbery** [schlagmichdoch/PairDrop#46] opened 2023-02-24 07:45 UTC
share menu with Android  not working

- Installed the PWA with Chrome
- if I open the PWA directly, it shows https://pairdrop.net as expected
- if I try to share via the share menu, select the pairdrop icon
  PWA starts but displays an ERR_FAILED (Website is not reachable)
  starting the PWA direct after the error direct, it works.
  
**Expected behavior**
both ways should work :-)

**Smartphone (please complete the following information):**
 - Samsung fold 4
 - OneUI 5.1 Android 13 
 - Chrome Browser 110.0.5481.65

**Self-Hosted**
No

**Self-Hosted Setup**
Proxy: Nginx | Apache2
Deployment: docker run | docker-compose | npm run start:prod

**Additional context**

**Comment by schlagmichdoch** [comment] 2023-02-24 11:17
Thanks for your issue.
Duplicate of #11 though. Please add any additional information there to bump this.
It’s under development.

**Closed by schlagmichdoch** 2023-02-24 11:17 UTC
