### ISSUE TITLE
Bug: Pairdrop PWA makes itself the default text editor

### ISSUE THREAD

**Issue by ghost** [schlagmichdoch/PairDrop#116] opened 2023-05-28 05:29 UTC
**Describe the bug**
When pairdrop is installed as a PWA, it makes itself the default text editor.

**To Reproduce**
1. Go to pairdrop
2. Click on install it as PWA
3. Open file manager and right click on a text file

**Expected behavior**
installing the PWA shouldn't replace the default app

**Screenshots**
![Screenshot from 2023-05-28 11-12-12](https://github.com/schlagmichdoch/PairDrop/assets/79187956/06ea16e4-e9bf-473d-a60e-f372fc81e502)

**Desktop (please complete the following information):**
 - OS: Fedora 38 Gnome
 - Browser: Chromium
 - Version: Version 113.0.5672.126 (Official Build) Fedora Project (64-bit)

**Self-Hosted**
No

**Comment by schlagmichdoch** [comment] 2023-05-28 13:10
This is similar to #17 

It depends on the OS and the Browser how the file handler api is integrated. Some browsers allow to switch it off.
On the other hand, you just have to select the normal text editor as standard again and the problem is resolved.

Maybe we have to remove this API if this is annoying for many users.

**Comment by unomi-zan** [comment] 2023-05-28 13:36
It would've been fine if it was only text files.
I've tested with many other file types and found out these file types are also affected:
- pdf
- every text file such as c, java, js, php, md
- zip
- penpot
- apk
- bin and many more
- and it sets itself as the default calendar app
> you just have to select the normal text editor as standard again and the problem is resolved.

There is no one click solution to set the default text editor graphically in Gnome at least.

**Comment by schlagmichdoch** [comment] 2023-05-30 14:41
I'm afraid this behaviour cannot be changed. It seems the OS always sets the newest PWA as default for its filetypes.

You have two options:
Firstly, all default apps can be handled centrally under `settings` > `default apps`. If you have done it once you will never be bothered again as the OS always prefers the newer app.
![Screenshot from 2023-05-30 10-25-16](https://github.com/schlagmichdoch/PairDrop/assets/52242352/46c84193-a49b-4235-9a38-5c9482bcaa4b)


Alternatively, you can go to `chrome://apps` on Google Chrome, right-click on PairDrop and select `settings` to get to the following menu. On the bottom you can switch off the File Handler Api completely. You can [use the cli](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#send-directly-via-command-line-interface) to send files instead.
![Screenshot from 2023-05-30 10-29-08](https://github.com/schlagmichdoch/PairDrop/assets/52242352/2ecf8d1a-856c-4258-b75f-f17cfe11c077)

**Comment by schlagmichdoch** [comment] 2023-12-13 18:43
This is fixed in version `v1.10.0`. The complete File Handling Api is removed as there have been too many incidents that it was rather annoying instead of helping. It is replaced by a way to use the _pairdrop-cli_ script to send from the context menu on Windows and Linux: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#send-multiple-files-and-directories-directly-from-context-menu-on-windows

**Closed by schlagmichdoch** 2023-12-13 18:43 UTC
Labels: enhancement

**Comment by schlagmichdoch** [comment] 2024-04-30 16:42
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

This is fixed in version `v1.10.0`. The complete File Handling Api is removed as there have been too many incidents that it was rather annoying instead of helping. It is replaced by a way to use the _pairdrop-cli_ script to send from the context menu on Windows and Linux: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#send-multiple-files-and-directories-directly-from-context-menu-on-windows
