### ISSUE TITLE
BUG: iOS Safari keeps Connecting every couple of seconds

### ISSUE THREAD

**Issue by fede777** [schlagmichdoch/PairDrop#128] opened 2023-07-18 23:16 UTC
Hi there, wanted to use snapdrop today and found out that now it's changed to this new PairDrop.

Tried using it on my 12 mini, but the Safari page keeps connecting all the time, it's a loop.

Screencap -> https://imgur.com/k4rUUEK

Is it just me?

**Comment by fede777** [comment] 2023-07-19 13:27
Ok, thanks for letting me now, hope it gets fixed.

**Comment by fede777** [comment] 2023-07-23 22:36
I'm using LocalSend while this gets fixed

**Comment by schlagmichdoch** [comment] 2023-07-25 16:55
I could not reproduce the issue but I have increased the reconnect timeout to give clients more time to load the page properly. Please test if this issue persists @fede777 @saiworksandbox

**Comment by schlagmichdoch** [comment] 2023-07-25 19:11
> It's working better now.

Okay let’s keep an eye on that then.
If the issue does not reappear in the next week, I will push the change to the current master.
 
 

> Another issue I see, maybe it's intended, but every time I tap Accept, to receive a file, it prompts the Share Sheet, even though I never tap Share. Is that normal?

That’s by design, to reduce the amount of clicks needed when receiving a file. Do you think this is unintuitive?

**Comment by fede777** [comment] 2023-07-25 19:52
Depends on what the user wants, the share sheet that appears right away, after you tap Accept, does not offer the option to save a picture or video to the Photos App.

So if I want to do that I have to dismiss the share sheet, tap download, and then choose View or Download from the Safari popup.

In that case, the amount of clicks is increased not reduced.

**Comment by schlagmichdoch** [comment] 2023-07-26 12:58
I‘m aware of that constraint on iOS and find it deeply annoying and unnecessary.

Luckily, there is a workaround:
See *How to save images directly to the gallery on iOS?* on https://github.com/schlagmichdoch/pairdrop/blob/master/docs/faq.md

**Comment by schlagmichdoch** [comment] 2023-07-27 09:49
I did some changes to the keep-alive logic. Please try again!

**Comment by schlagmichdoch** [comment] 2023-08-03 14:09
@fede777 Any news?

**Comment by schlagmichdoch** [comment] 2023-08-28 12:58
@fede777 Please give some feedback whether this is solved so I can either close this issue or investigate further

**Comment by schlagmichdoch** [comment] 2023-09-15 14:54
Closing this as resolved. Feel free to reopen if the issue occurs again.

**Closed by schlagmichdoch** 2023-09-15 14:54 UTC
Labels: bug, pairdrop.net

**Comment by schlagmichdoch** [comment] 2023-09-18 21:29
I fixed a bug in the latest version `v1.8.0` which is probably connected to this issue. You should not face this issue anymore on the official https://pairdrop.net
