### ISSUE TITLE
Bug:/Enhancement:/Feature Request: "No server connection. Retry in 5s..."

### ISSUE THREAD

**Issue by halictuz** [schlagmichdoch/PairDrop#27] opened 2023-02-12 18:01 UTC
**Describe the bug**
No server connection. Retry in 5s...

**To Reproduce**
1. Install Docker with the description here on github. 
2. start it up behind caddy reverse proxy
3. go to domain in browser
4. See error "No server connection. Retry in 5s..."

**Expected behavior**
Expect it to work even if "X-Forwarded-For" is not set. Or at least have the guide reflect that it wouldn't work at all without it. 

**Screenshots**
https://ibb.co/VSFJYpZ

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue / Fedora Workstation / Arch Linux
 - Browser: Librewolf, default Firefox, default Chromium
 - Version: All latest versions available (non beta)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 / Pixel 4
 - OS: GrapheneOS/Google Android
 - Browser: Vanadium / Android Chrome / Bromite
 - Version: latest non beta

**Additional context**
It also doesn't seem to work even with X-Forwarded-For set. Unless I got the synthax wrong for Caddy proxy, because there is only a description for Nginx and Apache unfortunately.

**Comment by schlagmichdoch** [comment] 2023-02-13 12:33
Literally the first sentence [in the docs in section HTTP-Server](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#http-server):
> When running PairDrop, the `X-Forwarded-For` header has to be set by a proxy. Otherwise, all clients will be mutually visible.

PairDrop is also working without setting up the header but than all connected clients are shown to everybody as they all seem to have the same IP address.

Probably this happens because your HTTP server does not route your websocket requests correctly. Therefore, those requests fail and the client shows a message that the server is not reachable. Be sure that websocket requests (wss) that are all pointing to `/server` are not redirected to https as they than fail.

Be sure to follow the documention and have a look at the Apache configuration example: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#using-apache
specifically:

```
	RewriteEngine on
	RewriteCond %{HTTP:Upgrade} websocket [NC]
	RewriteCond %{HTTP:Connection} upgrade [NC]
	RewriteRule ^/?(.*) "wws://127.0.0.1:3000/$1" [P,L]
```

**Comment by schlagmichdoch** [comment] 2023-02-13 12:33
Probably duplicate of #24

**Comment by schlagmichdoch** [comment] 2023-02-15 13:07
HTTP to HTTPS Redirect should be fine. Can you check whether this is implemented correctly? A websocket request (wss://) should not be redirected to https.

In the network tab in the developer tools if your browser you can check the answer of your request to `/server/webrtc`. It probably says sth like „a HTTP request can not be answered by a WS and fails“

I don’t know anything about caddy. If you provide your current caddy configuration for PairDrop I can have a look though

**Comment by ovizii** [comment] 2023-02-20 17:51
I am having a similar issue, and I am using traefik as reverse proxy. I previously used snapdrop. I use other containers behind the same reverse proxy which also need wss and they work. 

Let me see what I can contribute. If it sounds like a different issue, please let me know and I'll open my own thread. 

I have my self-hosted pairdop open in Chrome on my Android phone and on 2 Win 10/11 laptops. Only 1 laptop is in the same network as the phone. 

I checked the browser console and found these on the laptop NOT on the same network as the phone:
![image](https://user-images.githubusercontent.com/837902/220172862-5843989a-b89d-45a4-b48d-12b836011f3c.png)

On the laptop in the same network as the Android phone:
![image](https://user-images.githubusercontent.com/837902/220173158-83d3e469-10b6-483c-85b8-b56f49bad209.png)
![image](https://user-images.githubusercontent.com/837902/220173356-c4b3a594-0a46-4151-b89c-01b4c6916677.png)

**Comment by schlagmichdoch** [comment] 2023-03-06 11:37
I pushed some stability fixes in the last 2 weeks. Do these issues persist?

**Comment by ovizii** [comment] 2023-03-06 13:03
Those probs seem gone for me now, thanks.

**Comment by schlagmichdoch** [comment] 2023-03-06 14:41
Awesome! @halictuz what about you?

**Comment by schlagmichdoch** [comment] 2023-03-14 20:58
As @ovizii approved that this is not an issue anymore, I will close this for now. Feel free to reopen if the problem persists @halictuz

**Closed by schlagmichdoch** 2023-03-14 20:58 UTC
Labels: documentation, help wanted
