### ISSUE TITLE
Bug: Android Share Error "this site can't be reached"

### ISSUE THREAD

**Issue by kubafettMN** [schlagmichdoch/PairDrop#50] opened 2023-02-24 19:04 UTC
I saw that this feature is still being developed. But when Pairdop gets installed and it accessible from the android share menu it fails to load. "This site can't be reached" is but if you hit the hamburger menu and request it open in Chrome it opens up fine. The problem is when you do that you have to find and reselect the file you wanted to share in the first place.

**Comment by schlagmichdoch** [comment] 2023-03-06 18:47
Thanks for the additional Info!
If you want to help, I would appreciate, if you could test the following:
- can you share links/text with PairDrop via the context menu correctly and the issue is only with files or is this failing for both?
- Please try out this demo app, install it as a PWA and check whether you can share a link with it from the share-menu:
https://web-share-tar.glitch.me/
- Please try out these demo apps, install them as PWAs and check whether you can share a file with them from the share-menu:
https://mconverter.eu/
https://scrapbook-pwa.web.app/

I could then try to implement it like they do.

**Comment by holgerimbery** [comment] 2023-03-08 13:31
@schlagmichdoch: Same issue here. 

* both links/text and files failing

* https://web-share-tar.glitch.me/ app does not work as expected:

* both work as expected:   (https://mconverter.eu/ and https://scrapbook-pwa.web.app/) 

environment: chrome on Samsung fold 4 with android 13

**Comment by schlagmichdoch** [comment] 2023-03-08 14:58
@holgerimbery Thanks for testing! I will try to make it work with Android Studio and come back to you!

**Comment by schlagmichdoch** [comment] 2023-03-08 22:25
Somehow the api does not work in the Android emulator at all and right now I have no Android device at hand for testing. I will try to implement it by looking at the implementations that worked for you, if you could test it for me then. Ok?

**Comment by holgerimbery** [comment] 2023-03-09 05:23
@schlagmichdoch yes, of course, I will test, thank you for your work!

**Comment by ianwill93** [comment] 2023-03-09 14:35
I'd be willing to test too. This same bug occurs on ChromeOS

**Comment by schlagmichdoch** [comment] 2023-03-09 16:49
Nice! Then please install [this instance](https://pairdrop-dev.onrender.com/) as PWA and test:
- sharing a url
- sharing text
- sharing 1 file
- sharing multiple files

If the sharing seems to work, please also test if the file is uncorrupted on the receiving device.

**Comment by holgerimbery** [comment] 2023-03-09 17:33
@schlagmichdoch 
I did the following: 
I opened the link you provided with chrome 110.0.5481.153 on android 13 on a Samsung Fold 4 and installed the PVA.

When I open the PVA - 
I can send text and a single file and several files - it works as expected.

When I try to share via sharing menu - 
sending a URL or file(s) -> the PVA opens, but no sending action is performed.

Cheers
Holger

**Comment by schlagmichdoch** [comment] 2023-03-09 17:40
So the pwa is opening without any error but it does not say „Tap to send shared text“?

**Comment by ianwill93** [comment] 2023-03-09 17:46
I'm getting the same. The share sheet action opens the app, then nothing happens. It behaves as if I just opened the app from the launcher.

**Comment by holgerimbery** [comment] 2023-03-09 17:47
exactly, it opens, but no prompt.

**Comment by schlagmichdoch** [comment] 2023-03-09 18:25
I changed some things. could you try again? I'm not sure whether the service worker gets updated by simply reloading the pwa so better reinstall the pwa completely.

**Comment by holgerimbery** [comment] 2023-03-09 18:44
@schlagmichdoch: removed and reinstalled the PVA, but, sorry, no change - still no prompt

**Comment by schlagmichdoch** [comment] 2023-03-09 21:16
And this is the same for files as for links/text I assume, is it?

**Comment by holgerimbery** [comment] 2023-03-09 22:10
Yes, all the same...

**Comment by Jaonea** [comment] 2023-03-13 01:38
Experiencing the same issue
PWA app on itself works fine but using the android share menu does not.

It gives a timeout error as described by kubafettMN
![Screenshot_20230313-023305](https://user-images.githubusercontent.com/24249324/224588923-6c4059f3-7650-4d68-9c9d-219e886087b3.png)

The PWA app itself loads
![Screenshot_20230313-023406](https://user-images.githubusercontent.com/24249324/224588998-cd8897ab-c4e4-42d4-916b-69c7611326ae.png)

Tried using mconverter.eu through the share menu and that one works fine 
![Screenshot_20230313-023447](https://user-images.githubusercontent.com/24249324/224589037-9a3a2598-bbe8-4799-8211-2a9df8cf3b3a.png)

**Comment by schlagmichdoch** [comment] 2023-03-28 17:32
Thanks to @deancanen this should now be working 🎉

@holgerimbery @ianwill93 Could you please test again here: https://pairdrop-share-target.onrender.com?

I will merge this after as soon as I get your confirmation

**Comment by ianwill93** [comment] 2023-03-28 17:41
This is awesome! Just tried between Windows, Android, and ChromeOS. Everything worked as expected. Really good work!

**Comment by holgerimbery** [comment] 2023-03-28 17:56
Works between Android and Windows when started via sharing menu. Thanks - awesome!!

**Comment by schlagmichdoch** [comment] 2023-03-28 18:05
Perfect! Thanks for the quick testing! This is now merged into `v1.5.2` and live at https://pairdrop.net/

@kubafettMN Does this resolve your issue?

**Comment by taha-yassine** [comment] 2023-03-29 21:54
Awesome, this works!
Little tip for anyone struggling: try resetting the PWA  (for chrome on android: long press > site setttings > clear & reset).

**Closed** 2023-04-17 21:26 UTC
Labels: bug, duplicate, under development
