### ISSUE TITLE
[Bug] cf tunnel+device discovery not working 

### ISSUE THREAD

**Issue by rafalohaki** [schlagmichdoch/PairDrop#189] opened 2023-10-23 23:34 UTC
I try to host pairdrop and using cloudflare tunnel
i get log about connecting other device to network but its not loading fully and with error
i tried some ways but still not working

this is what i get when i set up  IPV6_LOCALIZE=true
![raw](https://github.com/schlagmichdoch/PairDrop/assets/20607107/67d9e2fc-f5e0-4734-ac02-edf06483c272)

this is when i set up IPV6_LOCALIZE=false

![raw](https://github.com/schlagmichdoch/PairDrop/assets/20607107/035d74b0-24de-4a7a-89e2-aa0ea88956a6)

with IPV6_LOCALIZE=4 i get
![raw](https://github.com/schlagmichdoch/PairDrop/assets/20607107/79b69f73-f78d-4693-b100-8f701d495b5d)
its discovering device in console but not in gui and after 3 seconds, there is an error.

should i set true to Disable Chunked Encoding/No Happy Eyeballs?
what env should i use
which ip exposed/local should i reverse to make it work woth cloudflare tunnel
I tried to solve problem looking through this issue https://github.com/schlagmichdoch/PairDrop/issues/69
but still no result

my docker compose:
---
version: "4"
services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop
    container_name: pairdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - RATE_LIMIT=false #optional
      - WS_FALLBACK=false #optional
      - RTC_CONFIG= #optional
      - DEBUG_MODE=false #optional
      - IPV6_LOCALIZE=4
    ports:
      - 3088:3000
    restart: unless-stopped

**Comment by schlagmichdoch** [comment] 2023-10-24 16:02
As the error message explains you need to deploy a TURN server alongside PairDrop for it to work behind Cloudflare.
See [Deployment notes](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#deployment-notes) for instructions.

Probably I should also provide a docker-compose file that does it all at once. I will look into it.

**Comment by alexonpeace** [comment] 2023-10-26 11:32
i got same issue i think only after recent update even without cf bypassed it wouldn't work on a different network

**Comment by schlagmichdoch** [comment] 2023-10-26 14:49
@alexonpeace have you deployed a TURN server? If at least one device is behind a NAT you need that for connections:

> <b>TURN server for Internet Transfer</b>
> 
> Beware that you have to host your own TURN server to enable transfers between different networks.
>
> Follow [this guide](https://gabrieltanner.org/blog/turn-server/) to either install coturn directly on your system (Step 1) \
> or deploy it via docker-compose (Step 5).

> Alternatively, use a free, pre-configured TURN server like OpenRelay

**Comment by schlagmichdoch** [comment] 2023-10-28 02:51
I have refactored the documentation and fixed the Docker Compose file to host coturn alongside PairDrop.

@alexonpeace @rafalohaki Please checkout this branch to test if everything is as easy as expected:

1. `git clone https://github.com/schlagmichdoch/PairDrop.git`
2. `cd PairDrop`
3. `git checkout fix-turn-container`
4. Follow the guide at https://github.com/schlagmichdoch/PairDrop/blob/fix-turn-container/docs/host-your-own.md#coturn-and-pairdrop-via-docker-compose

After your feedback I would merge this into master.

**Comment by schlagmichdoch** [comment] 2023-10-31 06:49
Corresponding PR: #195

**Comment by schlagmichdoch** [comment] 2023-12-13 17:27
The docker changes have since been released into `v1.10.0` so your can also find the documentation on the master branch:
https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#coturn-and-pairdrop-via-docker-compose

Have you since had any luck in hosting your PairDrop instance? :)

**Comment by rafalohaki** [comment] 2024-05-29 23:06
i used stun server from cloudflare. its working

**Comment by dforel** [comment] 2024-06-30 14:26
i use stun,its not working, i don't know where is wrong.

i use google'turn server（stun.l.google.com）, when i test webrtc on  https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/，its work，but，when i use my deploy pairdrop，it show rtc connection failed。

**Comment by schlagmichdoch** [comment] 2024-06-30 22:12
Closing this as stale. Feel free to reopen if the issue is still present.

**Closed by schlagmichdoch** 2024-06-30 22:12 UTC
Labels: bug

**Comment by andreapx** [comment] 2024-08-22 15:47
> i used stun server from cloudflare. its working

@rafalohaki can you share some info on how you did it?

**Comment by schlagmichdoch** [comment] 2024-08-23 11:14
> But it still doesn't see devices outside the same LAN that I pair.

You’ll need to run a turn server alongside PairDrop in order to achieve that:
https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#turn-server-for-internet-transfer

**Comment by andreapx** [comment] 2024-08-26 08:25
> > But it still doesn't see devices outside the same LAN that I pair.
> 
> You’ll need to run a turn server alongside PairDrop in order to achieve that: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#turn-server-for-internet-transfer

Oh, I thought that a STUN server was enough (sorry, I don't know much about STUN/TURN).
Thanks

**Comment by schlagmichdoch** [comment] 2024-08-26 12:15
There’s more info on the topic here:
https://github.com/schlagmichdoch/PairDrop/blob/master/docs/technical-documentation.md#encryption-webrtc-stun-and-turn

**Comment by andreapx** [comment] 2024-08-26 13:06
> There’s more info on the topic here: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/technical-documentation.md#encryption-webrtc-stun-and-turn

Thanks a lot! That helped me understand how it works.

**Comment by afly007** [comment] 2024-09-07 02:22
> i used stun server from cloudflare. its working

@rafalohaki any chance you have a config available to share?

**Comment by rafalohaki** [comment] 2024-09-07 19:01
> > i used stun server from cloudflare. its working
> 
> @rafalohaki any chance you have a config available to share?
rtc_config.json
![image](https://github.com/user-attachments/assets/3e047ec0-6b31-41bf-aaff-cde7806a2146)



`
version: "3"
services:
  pairdrop:
    image: "lscr.io/linuxserver/pairdrop:latest"
    container_name: pairdrop
    restart: unless-stopped
    volumes:
      - /root/docker/PairDrop/rtc_config.json:/home/node/app/rtc_config.json
    environment:
      - PUID=1000 # UID to run the application as
      - PGID=1000 # GID to run the application as
      - WS_FALLBACK=true # Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
      - RATE_LIMIT=false # Set to true to limit clients to 1000 requests per 5 min.
      - RTC_CONFIG=/home/node/app/rtc_config.json # Set to the path of a file that specifies the STUN/TURN servers.
      - DEBUG_MODE=false # Set to true to debug container and peer connections.
      - TZ=Europe/Warsaw # Time Zone
    ports:
      - "3002:3000" # Web UI. Change the port number before the last colon e.g. `127.0.0.1:9000:3000`

`
