### ISSUE TITLE
[Bug]  Files Fail to Transfer via Share - Mobile to Desktop

### ISSUE THREAD

**Issue by skykingisepic** [schlagmichdoch/PairDrop#196] opened 2023-10-31 10:44 UTC
**Describe the bug**
After selecting one or multiple image files and selecting share then SnapDrop app, in SnapDrop a popup at bottom shows 'File(s) selected for sharing - Cancel' then tapping on the Icon for Paired Device to send does nothing.

Note: On Desktop, Auto Accept is checked for paired mobile device. If auto accept is off, desktop gets popup asking to accept and if selected then 'waiting...' shows below paired device Icon and still no file transfer.

**To Reproduce**
1. Select Image File(s) in Messenger
2. Select Share
3. Select SnapDrop
4. Tap on Paired Device Icon to Send

**Expected behavior**
Files should transfer to selected paired device but nothing happens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Browser: Vivaldi
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: Pixel6
 - OS: GrapheneOS
 - Browser: Vivaldi
 - Version: latest
 - SnapDrop app v2.2.3
 - 
**Bug occurs on official PairDrop instance https://pairdrop.net/**
Unknown

**Bug occurs on self-hosted PairDrop instance**
Yes

**Self-Hosted Setup**
Proxy: None (running on LAN)
Deployment: docker run
Version: latest

**Additional context**

**Comment by schlagmichdoch** [comment] 2023-10-31 14:20
Hm that's weird. I'll try to reproduce this later as I'm not using the app (not maintained by me - independently developed)

It's not clear whether this is a problem of PairDrop or the android app.

Does file sharing work from the browser work when you are not using the App?

If you use Google Chrome on your Pixel phone, could you please install PairDrop as a PWA and share files to the PWA instead of to the Snapdrop app? Does it work then?

**Comment by skykingisepic** [comment] 2023-10-31 14:52
Using SnapDrop app, tapping on paired Desktop, and selecting file(s) to send works through my local PairDrop or pairdrop.net
Gallery allows selecting image(s) and has icon for direct snapdrop send (not available in share list from gallery)
PWA not showing in share list but shows on launcher as Vivaldi shortcut that defaults to pairdrop.net

Seems to be selecting images from SMS messages and sharing via SnapDrop that's causing the issue.

**Comment by schlagmichdoch** [comment] 2023-11-01 15:39
> PWA not showing in share list but shows on launcher as Vivaldi shortcut that defaults to pairdrop.net

This is because Vivaldi has not implemented PWA support on Android. You could install it via Chrome to have it appear in the share list. (https://firt.dev/notes/pwa/)

If you are sure this is app related, create an issue here: https://github.com/fm-sys/snapdrop-android

**Comment by schlagmichdoch** [comment] 2023-11-20 05:21
I’ll close this here. Best to reopen it in the snapdrop-android repo

**Closed by schlagmichdoch** 2023-11-20 05:21 UTC
Labels: bug
