### ISSUE TITLE
[Bug] iOS shortcut paste button not available

### ISSUE THREAD

**Issue by gponly** [schlagmichdoch/PairDrop#338] opened 2024-09-25 13:58 UTC
**Describe the bug**
When I share a file (picture for example), Pairdrop opens with the paste file tab, but nothing pasted in it. I have to paste manually the file still in the clipboard.

**To Reproduce**
1. Go to a file (a picture for example)
2. Click on share button and Pairdop (shortcut)
4. See that Pairdrop opens but the file is not paste in the popup

**Expected behavior**
I think the file is supposed to be pasted in the popup window

**Screenshots**

https://github.com/user-attachments/assets/29b1a009-8c33-4f32-81a7-be9ab4d97cce

**Smartphone (please complete the following information):**
 - Device: iPhone 16 Pro
 - OS: iOS 18
 - Browser: Safari

**Bug occurs on official PairDrop instance https://pairdrop.net/**
No

**Bug occurs on self-hosted PairDrop instance**
Yes

**Self-Hosted Setup**
Proxy: I don't know (installed via linuxserver/pairdrop on docker on a synology nas
Deployment: docker
Version: v1.10.10

**Additional context**

**Comment by rft91** [comment] 2024-09-28 07:42
me too

**Comment by gponly** [comment] 2024-10-10 13:55
Hi,
Thank you for your reply. I now host Airdrop via https and still, I can't have the file already paste in the field. I have still to do it myself even in https. Maybe it's what you tried to tell me (excuse me because I'm not english so I try to understand). Too bad... Maybe it's more a pull request than an issue if so.
Thank you for everything, it's still a very useful shortcut :)
Kind regards

**Comment by schlagmichdoch** [comment] 2024-10-10 14:38
Could you add another screencast to show me the current behavior?

**Comment by gponly** [comment] 2024-10-10 15:28
Here there are.

https://github.com/user-attachments/assets/fbd557fb-5af2-46dd-a8cb-78ff90ffb1a6

**Comment by schlagmichdoch** [comment] 2024-10-11 10:35
Thanks for the video! It seems like now your instance works as intended and equally to the instance on pairdrop.net.

The iOS shortcut uses the clipboard as a fast memory to transfer the data from a shortcut to the webpage. Sadly, the [Web Share Target API](https://developer.mozilla.org/en-US/docs/Web/Manifest/share_target) has not been implemented yet on iOS which would make this unnecessary. When this is implemented, like on Android Chrome or Samsung Internet, the user experience is much smoother after installing PairDrop as a PWA to the home screen.

As the issue is resolved, I'll close it.

**Closed** 2024-10-11 10:35 UTC
Labels: bug, self-hosted
