### ISSUE TITLE
Reported as dangerous?

### ISSUE THREAD

**Issue by fm-sys** [schlagmichdoch/PairDrop#102] opened 2023-04-10 11:41 UTC
Microsoft Edge reports pairdrop.net as dangerous. What happened here? Someone trying to sabotage pairdrop?

@schlagmichdoch maybe you could fill out the owner form clarifying that your website is not dangerous (at least I hope it is not)

![grafik](https://user-images.githubusercontent.com/64581222/230894206-1973b5b5-4805-4a01-9654-b19a5c1ea91a.png)

**Comment by schlagmichdoch** [comment] 2023-04-11 10:14
Thanks for reporting! This is probably similar to this snapdrop issue: https://github.com/RobinLinus/snapdrop/issues/573

You can also take a look at this FAQ: https://fb.smartscreen.microsoft.com/smartscreenfaq.aspx
I will use the contact form for website owners to report the warning as incorrect later. It would probably be helpful if everyone reports this as incorrect as well (see link above).

I hope this is resolved fast by Microsoft.

**Comment by schlagmichdoch** [comment] 2023-04-14 18:35
First I could not reproduce this issue until I recognized, that I had disabled microsoft SmartScreen.
After enabling it, I got the warning as well and reported it as false. This is their automatic receive confirmation which was funnily marked as malicious by my email program:
„Thank you for contacting us about https://pairdrop.net/.

We have received the information you provided and are currently reviewing it.  If it is determined that the current designation is incorrect or no longer accurate the warning will be removed.

We typically expect to take two business days for our investigation.  During the investigation, you may not see changes to the status of your site.  If the status of your site has not changed after two business days, please contact us with a reply to this message.  Please do not change the subject when replying.


You can find additional information by reviewing the Microsoft Defender SmartScreen
Overview - https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.

Thank you,
Microsoft Defender SmartScreen® Support“

I’ll keep you updated.

**Comment by schlagmichdoch** [comment] 2023-04-16 10:10
I have not yet received an answer from Microsoft but it seems the false warning is gone. When I visit pairdrop.net with enabled SmartScreen I do not get a warning anymore. Is this the same for you @fm-sys ?

**Comment by fm-sys** [comment] 2023-04-16 21:24
Yes, warning went away...

**Comment by schlagmichdoch** [comment] 2023-04-17 18:20
Very good! I will close this then. If it ever comes back, feel free to reopen this issue

**Closed by schlagmichdoch** 2023-04-17 18:20 UTC
Labels: bug

**Comment by fm-sys** [comment] 2023-09-08 08:39
Another time, some antivirus software reports PairDrop as dangerous. I have already filed a complaint, just so you know...


![grafik](https://github.com/schlagmichdoch/PairDrop/assets/64581222/d0b1b389-6dbe-4e7f-abfb-c9e72f46d68e)

**Comment by schlagmichdoch** [comment] 2023-09-08 14:27
Thanks for reporting as falsely flagged!
What does the report say?

**Comment by fm-sys** [comment] 2023-09-08 14:49
https://safeweb.norton.com/report/show?url=https://pairdrop.net/

Currently classified as Malware-Source/Malnets. I've requested to tag the website as file storage / share.

![grafik](https://github.com/schlagmichdoch/PairDrop/assets/64581222/6978bc24-c0e1-4a9b-a743-5ea8779e1726)
