### ISSUE TITLE
Safari on my iPhone won’t load the website properly at all

### ISSUE THREAD

**Issue by Cohenl19** [schlagmichdoch/PairDrop#210] opened 2023-11-28 05:38 UTC
I’m using an iPhone 13 on iOS 17.1.1, when I use Safari to go to “pairdrop.net” I run into a blank page with nothing on it.

I expect it to load up like usual but it doesn’t, I’ll attach a video showcasing what happens:

https://github.com/schlagmichdoch/PairDrop/assets/16529293/39f9c505-dd43-4fac-91c3-50cc19559625

**Comment by Cohenl19** [comment] 2023-11-28 05:39
I also tried it when turning off any Safari extensions I could have added, still no luck.

**Comment by schlagmichdoch** [comment] 2023-11-29 06:08
Wow, this is bad, I’m sorry! Do you have any other iPhones with that iOS version that you can check?

Have you visited pairdrop.net before and it worked as expected?

Please try again after deleting all website data:
Settings > Safari > Advanced > Website-data
After it finishes loading, type in *pairdrop.net*, swipe left and tap *delete*

Also, please test this instances to give me an idea whether the next version that will be deployed this week already includes fixes for this: https://pairdrop-dev.onrender.com

**Comment by Cohenl19** [comment] 2023-11-29 09:21
Also another thing I wanted to point out. When using https://sharedrop.io (which is another website with a GitHub very similar to PairDrop) between an iOS & Android device, there is no 200MB limitation. With PairDrop is there a way to remove this like with ShareDrop? I tested it on this website and it worked fine with a file over 200MB. Both use WebRTC right? So would this be possible?

**Comment by schlagmichdoch** [comment] 2023-11-29 17:00
Thanks for reporting back!

> I love the AMOLED Black background on that one so I might just use that.

Beware that I use that as a test and playground so this page is constantly changing. I will merge the new changes this week so don't worry about missing out on the AMOLED black :wink: 



> Also I’ll add that it worked on the Google & Chrome app at the same time it didn’t work on my Safari yesterday, which I found very odd.

I'm glad it's resolved and hopefully it will never be an issue again after the new changes are merged. Not having it reproducible is never good but I cannot do anything right now so I'll close this. If it ever happens again I'd appreciate if you would reopen this issue with more information!



> where the circles moves as they get bigger in the background

The background animation is abolished purposely. Firstly, the behavior is inconsistent as implemented into Snapdrop, as it does not start again when all peers have left. This was fixed in the beginning of PairDrop. But secondly, this animation (and all versions with a smarter logic I tried) are a heavy strain on CPU and/or GPU. See https://github.com/schlagmichdoch/PairDrop/issues/75 and https://github.com/schlagmichdoch/PairDrop/commit/b42c8a0b1a1e0522af2b21a7d980183627735cd3
In the end I decided to remove the background animation in favor of speed and efficiency. I also prefer the calmness of the GUI when the PWA is running all the time.

If you really miss this, please create a new separate issue for it. If enough users really do like the animation I will try to come up with a way without it straining the CPU/GPU (probably removing transparency changes would help).



> Also another thing I wanted to point out. When using https://sharedrop.io (which is another website with a GitHub very similar to PairDrop) between an iOS & Android device, there is no 200MB limitation. With PairDrop is there a way to remove this like with ShareDrop? I tested it on this website and it worked fine with a file over 200MB. Both use WebRTC right? So would this be possible?

Which iPhone and iOS do you use? What's the biggest file you could transfer **to** the iPhone without sharedrop crashing? The problem is that the memory we can use on iPhones is quite restricted. I plan to rewrite the File Chunking logic anyways so maybe I can find a way to increase the limitation. I'll create a separate issue for that

**Closed by schlagmichdoch** 2023-11-29 17:00 UTC
Labels: bug, not reproducible, pairdrop.net

**Comment by schlagmichdoch** [comment] 2024-04-30 17:02
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

Wow, this is bad, I’m sorry! Do you have any other iPhones with that iOS version that you can check?

Have you visited pairdrop.net before and it worked as expected?

Please try again after deleting all website data:
Settings > Safari > Advanced > Website-data
After it finishes loading, type in *pairdrop.net*, swipe left and tap *delete*

Also, please test this instances to give me an idea whether the next version that will be deployed this week already includes fixes for this: https://pairdrop-dev.onrender.com

Comment by @schlagmichdoch:
---

Thanks for reporting back!

> I love the AMOLED Black background on that one so I might just use that.

Beware that I use that as a test and playground so this page is constantly changing. I will merge the new changes this week so don't worry about missing out on the AMOLED black :wink: 



> Also I’ll add that it worked on the Google & Chrome app at the same time it didn’t work on my Safari yesterday, which I found very odd.

I'm glad it's resolved and hopefully it will never be an issue again after the new changes are merged. Not having it reproducible is never good but I cannot do anything right now so I'll close this. If it ever happens again I'd appreciate if you would reopen this issue with more information!



> where the circles moves as they get bigger in the background

The background animation is abolished purposely. Firstly, the behavior is inconsistent as implemented into Snapdrop, as it does not start again when all peers have left. This was fixed in the beginning of PairDrop. But secondly, this animation (and all versions with a smarter logic I tried) are a heavy strain on CPU and/or GPU. See https://github.com/schlagmichdoch/PairDrop/issues/75 and https://github.com/schlagmichdoch/PairDrop/commit/b42c8a0b1a1e0522af2b21a7d980183627735cd3
In the end I decided to remove the background animation in favor of speed and efficiency. I also prefer the calmness of the GUI when the PWA is running all the time.

If you really miss this, please create a new separate issue for it. If enough users really do like the animation I will try to come up with a way without it straining the CPU/GPU (probably removing transparency changes would help).



> Also another thing I wanted to point out. When using https://sharedrop.io (which is another website with a GitHub very similar to PairDrop) between an iOS & Android device, there is no 200MB limitation. With PairDrop is there a way to remove this like with ShareDrop? I tested it on this website and it worked fine with a file over 200MB. Both use WebRTC right? So would this be possible?

Which iPhone and iOS do you use? What's the biggest file you could transfer **to** the iPhone without sharedrop crashing? The problem is that the memory we can use on iPhones is quite restricted. I plan to rewrite the File Chunking logic anyways so maybe I can find a way to increase the limitation. I'll create a separate issue for that
