### ISSUE TITLE
Devices do not see each other. PC <-> Smartphone

### ISSUE THREAD

**Issue by killtux** [schlagmichdoch/PairDrop#21] opened 2023-02-10 16:11 UTC
if i open PairDrop on the PC (Windows) and Smartphone (iOS) i cant see each other, even if i pair the devices successfully.
I can send files to other Smartphones (iOS) and i can see my computer itself as seperate device if i open it in two browsers.

Sometimes if i wait 1-2 minutes i see the device but most times not at all. from time to time i get "You are back online." message at the smartphone.

if i opened snapdrop, both devices saw each other instantly. any idea what is causing this?

**Comment by schlagmichdoch** [comment] 2023-02-10 23:06
I just pushed some stability fixes that should resolve this issue. Could you try again?

**Comment by killtux** [comment] 2023-02-13 17:48
i got it working two times (out of 20 tries), but for most devices dont see each other and i can't see why its working sometimes.

**Comment by schlagmichdoch** [comment] 2023-02-13 18:03
hm.. have you tried clearing the browser data for pairdrop.net on all devices? I cannot reproduce this issue with windows 11 + iOS or via any configuration on Browserstack. Do you get any error messages? Do you use a VPN?

**Comment by schlagmichdoch** [comment] 2023-02-13 20:49
The animation is stopped as soon as a peer is connected successfully.
On snapdrop, devices are shown as soon as both open Snapdrop. PairDrop ensures that the peer to peer connection is established successfully before showing a device. This way you will never interact with a device that is not connected yet.
It may well be that sending files over Snapdrop does not work with your configuration as well, even though the devices are shown.

Your guess about VPN blocking is probably correct. WebRTC needs to be enabled for PairDrop to work. Often you need to enable webrtc specifically in your VPN settings

**Comment by schlagmichdoch** [comment] 2023-02-15 17:59
Any news?

**Comment by killtux** [comment] 2023-02-16 12:13
i noticed its working when my pc connects through lan and i use firefox or edge (no extensions installed). on chrome and brave i dont see the other device. maybe an extension is blocking it.

when i connect through ethernet dont see a device at all, no matter what browser.

i tried it on 3 other computers in my lan an everywhere it worked. looks like its a more specific problem with my desktop pc 🤔

**Comment by schlagmichdoch** [comment] 2023-02-16 12:25
Does your browser console throw any errors?
If you visit the following page with the affected browsers, what does it say beneath „Browser supports WebRTC“?
https://www.webrtc-experiment.com/DetectRTC/#isWebRTCSupported

**Comment by killtux** [comment] 2023-02-16 12:46
sorry i forgot: sure WebRTC is supported.

Dev Tools Console:
![image](https://user-images.githubusercontent.com/36768145/219368563-85270508-47da-41bf-bba8-aa25fd6deca5.png)

**Comment by schlagmichdoch** [comment] 2023-02-16 13:09
Thanks but that is the dev console for Snapdrop 😉

**Comment by killtux** [comment] 2023-02-16 13:30
oh man sorry. 😅

![image](https://user-images.githubusercontent.com/36768145/219378096-40bd6462-5e3c-412b-96a2-8b3437d8d0a7.png)

![image](https://user-images.githubusercontent.com/36768145/219378133-a1f49e5d-b7cd-441e-b98a-50373e6ec460.png)

![image](https://user-images.githubusercontent.com/36768145/219378152-7dc52cc1-7b62-4330-a2d4-b243c7db4358.png)

**Comment by schlagmichdoch** [comment] 2023-03-06 22:01
The last 3 weeks brought many stability improvements. I’d appreciate, if you could test again whether that pc of yours is still not connecting!

**Comment by killtux** [comment] 2023-03-08 19:16
still no connection in my specific situation (desktop win10 LAN <-> iPhone WiFi). all other combinations work.

**Comment by schlagmichdoch** [comment] 2023-03-14 21:29
Are your LAN and WiFi two separate NATs meaning you cannot ping devices on LAN from devices on WiFi or vice versa? If so that would probably require a TURN server which would make this issue the same problem as #71

**Comment by acupofjose** [comment] 2023-03-15 00:55
@killtux I think I found the issue! Do you have the ["Limit IP Address tracking"](https://support.apple.com/en-us/HT212614#:~:text=Go%20to%20Settings%2C%20then%20tap,tap%20Limit%20IP%20Address%20Tracking.) setting turned on for the network you're on for your iphone? Turned it off it and connected via websocket immediately.

**Comment by killtux** [comment] 2023-03-15 21:10
turned it off but still no connection. i think it has todo with my pc since
all other combinations with the other pc's work.

Am Mi., 15. März 2023 um 01:55 Uhr schrieb Joseph Schultz <
***@***.***>:

**Comment by schlagmichdoch** [comment] 2023-04-17 21:42
Maybe this is also connected to #71 
I have added a new TURN server to enable sending between devices behind different NATs. Does this resolve your issue?

**Comment by killtux** [comment] 2023-04-18 08:09
looks like it solved the issue. 😎🎉 
devices can now see each other instantly.

**Comment by schlagmichdoch** [comment] 2023-04-18 10:02
Awesome, glad it works! 🥳 I’ll close this issue for now then. Feel free to reopen if you hit on problems again.

**Closed by schlagmichdoch** 2023-04-18 10:02 UTC
Labels: not reproducible
